---
- name: Tao vm - ip tren netbox
  hosts: all
  gather_facts: false
  connection: local


  vars:
    netbox_url: http://10.0.11.182:8000/
    netbox_token: 0123456789abcdef0123456789abcdef01234567

#    vm_cluster: my_vm_cluster
#    vm_name: ngocpro01
#    vm_role: "Virtual Machine"
#    vm_interface: ens192
#    vm_address: 192.168.0.124/24

  tasks:
    - name: create vm sample
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vm_name }}"
          cluster: "{{ vm_cluster }}"
          virtual_machine_role: "{{ vm_role }}"
      delegate_to: localhost

    - name: create intarface each vm
      netbox.netbox.netbox_vm_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          virtual_machine: "{{ vm_name }}"
          name: "{{ vm_interface }}"
      delegate_to: localhost

    - name: create ip address and assign
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ vm_address }}"
          assigned_object:
            name: "{{ vm_interface }}"
            virtual_machine: "{{ vm_name }}"
      delegate_to: localhost

    - name: update vm primary_ip4
      netbox.netbox.netbox_virtual_machine:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ vm_name }}"
          cluster: "{{ vm_cluster }}"
          virtual_machine_role: "{{ vm_role }}"
          primary_ip4: "{{ vm_address }}"
      delegate_to: localhost
